In [1]:
import pandas as pd

path = r"C:\Users\91916\Dropbox\GitHub\sicence nationism\migration_data\Global-flows-and-rates-of-international-migration-of-scholars-2026_V2\2026_V2\openalex_2026_V2_scholarlymigration_countryflows.parquet"

In [2]:
df = pd.read_parquet(path)
print(df.shape)
df.head()

(1455932, 14)

,n_migrations,year,gender,field,iso3codefrom,iso3codeto,countrynamefrom,countrynameto,paddedpopfrom,paddedpopto,number_of_outmigrationsfrom,number_of_inmigrationsto,normalized_migration1,normalized_migration2
0,1,1998,all,AgEnNat,AFG,KOR,Afghanistan,South Korea,4.0,32246.0,1.0,697.0,143472.022956,7.752900e+05
1,1,1998,all,all,AFG,KOR,Afghanistan,South Korea,7.0,55580.0,1.0,1297.0,77101.002313,2.570298e+05
2,1,1998,m,AgEnNat,AFG,KOR,Afghanistan,South Korea,2.0,11276.0,1.0,262.0,381679.389313,4.434197e+06
3,1,1998,m,all,AFG,KOR,Afghanistan,South Korea,3.0,18404.0,1.0,442.0,226244.343891,1.811200e+06
4,1,1998,all,AgEnNat,ALB,DEU,Albania,Germany,83.0,83393.0,7.0,3408.0,4191.817572,1.444749e+04

In [3]:
df.year

0          1998
1          1998
2          1998
3          1998
4          1998
           ...
1455927    2022
1455928    2022
1455929    2022
1455930    2022
1455931    2022
Name: year, Length: 1455932, dtype: int64

In [6]:
df1 = pd.read_csv(r'C:\Users\91916\Dropbox\GitHub\sicence nationism\migration_data\Global-flows-and-rates-of-international-migration-of-scholars-2026_V2\2026_V2\openalex_2026_V2_scholarlymigration_countryflows.csv')
df1

,n_migrations,year,gender,field,iso3codefrom,iso3codeto,countrynamefrom,countrynameto,paddedpopfrom,paddedpopto,number_of_outmigrationsfrom,number_of_inmigrationsto,normalized_migration1,normalized_migration2
0,1,1998,all,AgEnNat,AFG,KOR,Afghanistan,South Korea,4.0,32246.0,1.0,697.0,143472.023000,7.752900e+05
1,1,1998,all,all,AFG,KOR,Afghanistan,South Korea,7.0,55580.0,1.0,1297.0,77101.002310,2.570298e+05
2,1,1998,m,AgEnNat,AFG,KOR,Afghanistan,South Korea,2.0,11276.0,1.0,262.0,381679.389300,4.434197e+06
3,1,1998,m,all,AFG,KOR,Afghanistan,South Korea,3.0,18404.0,1.0,442.0,226244.343900,1.811200e+06
4,1,1998,all,AgEnNat,ALB,DEU,Albania,Germany,83.0,83393.0,7.0,3408.0,4191.817572,1.444749e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,2018,all,MhS,GHA,THA,Ghana,Thailand,4039.0,18536.0,137.0,430.0,3395.009336,2.671407e+03
1048571,2,2018,all,all,GHA,THA,Ghana,Thailand,10691.0,44184.0,354.0,1045.0,540.642824,4.233959e+02
1048572,1,2018,f,MhS,GHA,THA,Ghana,Thailand,1123.0,5851.0,39.0,138.0,18580.453360,1.521914e+04
1048573,1,2018,f,all,GHA,THA,Ghana,Thailand,2390.0,12492.0,71.0,271.0,5197.235071,3.349424e+03
1048574,1,2018,u,MhS,GHA,THA,Ghana,Thailand,425.0,10504.0,24.0,202.0,20627.062710,2.240043e+04

In [8]:
import pandas as pd
OPENALEX_FLOWS = pd.read_parquet(r'C:\Users\91916\Dropbox\GitHub\sicence nationism\migration_data\Global-flows-and-rates-of-international-migration-of-scholars-2026_V2\2026_V2\openalex_2026_V2_scholarlymigration_countryflows.parquet')
OPENALEX_FLOWS

,n_migrations,year,gender,field,iso3codefrom,iso3codeto,countrynamefrom,countrynameto,paddedpopfrom,paddedpopto,number_of_outmigrationsfrom,number_of_inmigrationsto,normalized_migration1,normalized_migration2
0,1,1998,all,AgEnNat,AFG,KOR,Afghanistan,South Korea,4.0,32246.0,1.0,697.0,143472.022956,7.752900e+05
1,1,1998,all,all,AFG,KOR,Afghanistan,South Korea,7.0,55580.0,1.0,1297.0,77101.002313,2.570298e+05
2,1,1998,m,AgEnNat,AFG,KOR,Afghanistan,South Korea,2.0,11276.0,1.0,262.0,381679.389313,4.434197e+06
3,1,1998,m,all,AFG,KOR,Afghanistan,South Korea,3.0,18404.0,1.0,442.0,226244.343891,1.811200e+06
4,1,1998,all,AgEnNat,ALB,DEU,Albania,Germany,83.0,83393.0,7.0,3408.0,4191.817572,1.444749e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455927,1,2022,f,AgEnNat,ZWE,ZMB,Zimbabwe,Zambia,0.0,0.0,29.0,13.0,265251.989390,NaN
1455928,1,2022,f,all,ZWE,ZMB,Zimbabwe,Zambia,0.0,0.0,76.0,49.0,26852.846402,NaN
1455929,1,2022,m,AgEnNat,ZWE,ZMB,Zimbabwe,Zambia,0.0,0.0,64.0,49.0,31887.755102,NaN
1455930,1,2022,m,HumSS,ZWE,ZMB,Zimbabwe,Zambia,0.0,0.0,35.0,17.0,168067.226891,NaN
1455931,2,2022,m,all,ZWE,ZMB,Zimbabwe,Zambia,0.0,0.0,121.0,101.0,16365.272891,NaN

In [10]:
OPENALEX_FLOWS.year.max()

np.int64(2022)